from module_1.classes.llm_prompter import (
    AgentResponse,
    FunctionCallResponse,
    LLMPrompter,
    MessageResponse,
)
from module_1.classes.thread import Thread
from module_1.classes.toolset import Toolset


class Agent():
    def __init__(self, prompter: LLMPrompter, thread: Thread):
        self._prompter = prompter
        self._thread = thread

    def invoke(self, toolset: Toolset, model: str = "nemotron-3-ultra:cloud", verbose: bool = False) -> str:
        """Runs an agentic loop until the model returns a final response

        :param toolset: Set of tools the agent can work with
        :param model: Name of the LLM model to work with
        :param verbose: Pass True to print intermediate model responses
        :return: The final text generated by the model
        """
        tools = toolset.get_definitions()
        callbacks = toolset.get_callbacks()

        while True:
            if verbose:
                print("Thread antes del llamado:", self._thread.get_input())

            response: AgentResponse = self._prompter.agentic_call(self._thread, tools, model=model)

            if verbose:
                print("Response:", response, "\n")

            message_texts = []
            tool_called_flag = False

            for item in response.data:
                match item:
                    case i if type(i) is MessageResponse:
                        self._thread.add_assistant_text(item.text)
                        message_texts.append(item.text)

                    case i if type(i) is FunctionCallResponse:
                        self._thread.add_function_call(
                            item.call_id, item.name, item.arguments
                        )
                        call_result = callbacks[item.name](**item.arguments)  # type: ignore
                        self._thread.add_function_call_output(
                            item.call_id, call_result
                        )
                        tool_called_flag = True

                    case _:
                        pass

            if not tool_called_flag:
                return "\n".join(message_texts).strip()
